gocd/docs.go.cd

configuration/configuration_reference.md
For issue #1 
also add document for `GO_FROM_REVISION` and `GO_TO_REVISION`
=> Document for new git material shallow clone option

installation/install/server/linux.md
=> Revert "Use better names for some headings"

beta/plugin_upload.md
* Upload Plugins feature is controlled through System Environment, docs updated for the same
=> Updated Upload Plugins docs

advanced_usage/command_repository.md
See: 
https://github.com/gocd/gocd/blob/master/server/webapp/WEB-INF/rails.new/spec/controllers/api/commands_controller_spec.rb#L23
We should also document this request in api.go.cd in the release notes : https://github.com/gocd/gocd/releases/tag/16.3.0
=> Update API request to reload command repository with new constraint

INTRO.md, advanced_usage/config_repo.md
Intro page and config repo garbage collection pages
=> Improve intro page and config repo garbage collection docs

configuration/configuration_reference.md
This feature was added by https://github.com/gocd/gocd/pull/2314
=> Documents `invertFilter`

configuration/configuration_reference.md
* documentation for `<agentConfig/>` element on a `<job/>`
* documentation for `elasticAgentId` and `elasticPluginId` attributes of `<agent/>`
=> Added elastic agent attributes and elements

installation/troubleshoot_installer.md
* Add information about the case of mismatched TLS certificates, caused
by changing the server an agent should connect to.
=> Add to troubleshooting guide - SSL handshake exception or connection reset

installation/install/_apt_repo.md, installation/install/_yum_repo.md, installation/install/agent/linux.md, installation/install/server/linux.md
=> Install Java 8 instead of Java 7

installation/install/agent/windows.md, installation/install/server/windows.md
The build was failing for the PR: #84. I ran this locally and it seems to work fine. So please review this and I'll be closing out the PR: #84.
=> Update to the docs(Agent/Server) when run by a local user account.

installation/install/agent/windows.md
=> Document the `START_AGENT` flag on the windows installer.

book.json
This will end up creating a sitemap in each branch, but I think that should be ok. Also, the cache time is not configurable. :(
@loudaTW wanted this.
/cc @varshavaradarajan
=> Add a sitemap

book.json
Backport https://github.com/gocd/docs.go.cd/commit/55012608de5614de7eea915fc6556b3e0acf0a0f
Equivalent of: https://github.com/gocd/docs.go.cd/pull/108
=> Backport sitemap

installation/install/agent/linux.md
=> Fix install docs: GO_SERVER => GO_SERVER_URL

configuration/configuration_reference.md
* Create a new section for config repo materials
* Show only required attributes for specific materials
=> Config repo material attribute change

configuration/dev_authentication.md
Merge it only if we are merging https://github.com/gocd/gocd/pull/4099
=> Updated documentation to mention about session related JVM args

configuration/configuration_reference.md
Added " on the agent side" to ensure user understands this action more accurately
=>  specify fetch materials option acts on agent side

release_history/whats_new_in_go.md
=> (minor) fix grammar

advanced_usage/admin_spawn_multiple_jobs.md, configuration/configuration_reference.md, configuration/dev_authentication.md, configuration/dev_upload_test_report.md, configuration/managing_a_build_cloud.md, extension_points/package_repository_extension.md, extension_points/scm_extension.md, extension_points/yum_repository_poller.md, faq/artifact_integrity.md, faq/rm_deploy_to_environment.md, installation/configure-agent-proxy.md, installation/configure-reverse-proxy.md, installation/performance_tuning.md, installation/system_requirements.md, navigation/agent_details.md, navigation/stage_details_page.md
=> Propose fix typos

advanced_usage/logging.md
This is just an example working setup which I tested. Might be useful for others.
=> added example logging configuration with graylog

advanced_usage/one_click_backup.md
Do not merge until this PR is merged https://github.com/gocd-private/extensions-docs.gocd.org/pull/42
=> added plugins not backed up and postgresql addon link

advanced_usage/logging.md
@ketan added this section, please let me know what do you think
=>  Addded override existing logback.xml section in logging.md

SUMMARY.md, installation/ssl_tls/configuring_hsts_header.md
Adding a screenshot since the diff looks yuck
=> Add documentation for configuring HSTS header

.gitignore, Gruntfile.js, README.md, content/configuration/elastic_agents.md, content/menu/index.md, layouts/partials/search/search.html, package.json, rakelib/build.rake, static/javascripts/search/search.js, themes/hugo-book/assets/book.scss, themes/hugo-book/layouts/_default/baseof.html, themes/hugo-book/layouts/_default/list.html, themes/hugo-book/layouts/_default/single.html, themes/hugo-book/layouts/partials/docs/html-head.html, yarn.lock
Link to the issue: #245.
/cc @streisguth @chandrakanth17 - Please feel free to change the styles for the search functionality.
=> Added search functionality.

static/javascripts/navigation/navigation.js, themes/hugo-book/assets/_variables.scss, themes/hugo-book/assets/book.scss, themes/hugo-book/layouts/_default/baseof.html, themes/hugo-book/layouts/partials/docs/html-head.html, themes/hugo-book/layouts/partials/docs/page-navigation.html
This is WIP. Styling bit is not finalized yet. There are issues with the container alignments across various screen size. Asked @naveenbhaskar to help us out with the same.
=> Added navigation functionality to docs

Gruntfile.js, content/advanced_usage/logging.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/_index.md, package.json, rakelib/build.rake, static/javascripts/search/search.js, themes/hugo-book/assets/book.scss, themes/hugo-book/layouts/_default/list.html, themes/hugo-book/layouts/_default/single.html, themes/hugo-book/layouts/partials/docs/html-head.html, yarn.lock
Improved indexing for search:
1. Added keywords and description
2. Stored the index in the JSON file and loaded the same at run time. Previously it was created at run time
3. Removed the stemmer function
4. Used gray-matter for reading MD files and separating out the front matter and content - earlier split was used which failed if the MD file contains a table.
5. Used markdown to store rendered content in the index instead of markdown content.
6. Added search title
7. Replaced var with const/let.
=> Improving lunr based search

content/integration/_index.md
=> Fix image links

content/installation/_index.md
=> Fix broken links on installation page

content/configuration/configuration_reference.md
* https://github.com/gocd/gocd/issues/6170
=> Rename profiles tag to agentProfiles

build.gocd.groovy, content/_index.md, content/advanced_usage/config_repo.md, content/advanced_usage/one_click_backup.md, content/advanced_usage/other_config_options.md, content/configuration/configuration_reference.md, content/extension_points/_index.md, content/extension_points/scm_extension.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/_index.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_build_pipeline.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_deploy_pipeline.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_test_pipeline.md, content/gocd_on_kubernetes/gocd_helm_chart/troubleshooting.md, content/gocd_on_kubernetes/introduction.md, content/installation/configure_proxy.html, layouts/alias.html, rakelib/build.rake, rakelib/static_checks.rake, themes/hugo-book/layouts/partials/docs/html-head.html
The link checker didn't take into account the internal links. Added that.
Fixed the links revealed by the same.
=> Improving link checkers

content/gocd_on_kubernetes/docker_workflows.md, content/gocd_on_kubernetes/helm_install.md, content/gocd_on_kubernetes/importing_a_sample_workflow.md, content/gocd_on_kubernetes/setup_and_configuration.md
Removes '$' prompts in code snippets.
=> Removes '$' prompts in code snippets

content/configuration/configuration_reference.md
GoCD issue: gocd/gocd#6294
PR: gocd/gocd#6411
* Add attribute `allowOnlyOnSuccess` under `approval`
=> Add attribute allowOnlyOnSuccess under approval.

content/gocd_on_kubernetes/introduction.md
The items in this list have to be done sequentially. Also modified grammar so all list items finish the sentence started by text like *With this documentation guide, you'll be able to....*
=> Modified grammar and added numbers

content/gocd_on_kubernetes/introduction.md, content/gocd_on_kubernetes/setup_and_configuration.md
=> Fix typos and broken links

.gitignore, content/advanced_usage/one_click_backup.md
Related to https://github.com/gocd/gocd/issues/7301 and https://github.com/gocd/gocd/pull/7312
=> Tanuki wrapper backup

content/configuration/configuration_reference.md
=> Document <policy> tag under role

content/advanced_usage/compare_pipelines.md
Related GoCD PR: https://github.com/gocd/gocd/pull/7879
=> Add a section for bisect pipeline instance warning

themes/hugo-book/assets/stylesheets/_variables.scss, themes/hugo-book/assets/stylesheets/book.scss
It seems too small. Also, improve the main docs page image size a bit.
The CSS is still not right. Doesn't change properly with a changing window size, but it'll do for now.
=> Make body column wider

content/introduction/concepts_in_go.md
ENV_STG has been set to 2 at 'pipeline' level and has been set to 3 at 'stage' level as per the given diagram in the dcumentation.
=> Update the level for ENV_STG = 2 to pipeline

Gemfile.lock, package-lock.json, package.json
Trying to see if a weird failure happening in the pipeline is fixed by upgrading hugo.
https://build.gocd.org/go/tab/build/detail/docs.gocd.org-master/258/Build/1/BuildWebsite
=> Upgrade gems and npm packages

content/installation/configuring_database/connection-properties.md, content/installation/configuring_database/mysql.md, content/installation/configuring_database/postgres.md, content/installation/upgrade_to_gocd_20.5.0.md
A bit around troubleshooting mostly.
-----------------------------------
In the MySQL page:
=> Improve MySQL-related docs

content/installation/configuring_database/h2.md, content/installation/configuring_database/mysql.md, content/installation/upgrade_to_gocd_20.5.0.md, layouts/partials/installation/configuring_database/_h2_troubleshooting.md, layouts/partials/installation/configuring_database/_mysql_troubleshooting.md
Show troubleshooting docs in H2 and MySQL pages too.
=> Show troubleshooting docs near DB docs (as well)

content/_index.md, content/advanced_usage/one_click_backup.md, content/installation/configuring_database/mysql.md, content/installation/configuring_database/postgres.md, content/installation/performance_tuning.md
Mostly around one-click backup.
=> Update more documentation for DB changes

content/installation/configuring_database/postgres.md
It was referred to another database
=> Correct the name of the database to assign the permissions

content/installation/install/agent/osx.md, content/installation/install/server/osx.md
Cherrypicked https://github.com/gocd/docs.go.cd/pull/476 on to current release.
=> [Current release] Add quarantine instructions to Mac OS X docs

.github/workflows/build_and_publish.yml, .github/workflows/pr_workflow.yml, .github/workflows/publish_older_releases.yml, .github/workflows/publish_release-19.10.0.yml, .github/workflows/publish_release-19.11.0.yml, .github/workflows/publish_release-19.12.0.yml, .github/workflows/publish_release-20.1.0.yml, .github/workflows/publish_release-20.10.0.yml, .github/workflows/publish_release-20.2.0.yml, .github/workflows/publish_release-20.3.0.yml, .github/workflows/publish_release-20.4.0.yml, .github/workflows/publish_release-20.5.0.yml, .github/workflows/publish_release-20.6.0.yml, .github/workflows/publish_release-20.7.0.yml, .github/workflows/publish_release-20.8.0.yml, .github/workflows/publish_release-20.9.0.yml, rakelib/upload.rake
Add a pipelines to 
- test the PRs via github actions
- build the current master and publish the same
- build the last 12 releases nd publish the same as well
=> Update to github actions

content/installation/upgrading_go.md
Changes values from 
`sudo rpm -Uvh /path/to/go-server-${version}.deb` 
to 
`sudo rpm -i /path/to/go-server-${version}.rpm`
=> updates the RPM based installation notes

content/advanced_usage/admin_install_multiple_agents.md
Adding link to the exact page can help end users to navigate easily
=> Adds link to the README-running-multiple-agents.md

content/installation/configuring_database/mysql.md
Builds is currently failing due to change in location of this documentation on MySQL side.
=> Update MySQL errors link to new location of documentation

.github/workflows/build_and_publish.yml
Using IAM Role with GHA OIDC provider to get the AWS Credentials for syncing with S3 bucket.
=> Using GHA OIDC IAM role to sync the artifacts with S3 bucket.

content/configuration/admin_add_task.md
As new user GoCD  I propose adding example usage of GoCD command task for experimenting and learning.
=> Docs examples on how to execute command task
