installation/configure_proxy.md, installation/install/agent/osx.md
Clearly explain how adding a proxy will still require access to the SSL server port for agents.
Also document how the port can be set for the Mac agent, but add a warning because you probably don't want to do this.
The Linux page already refers to the `/etc/default/go-agent` file, which contains the `GO_SERVER_PORT` key, so extra info is probably not necessary there.
Based on gocd/gocd#2032 and gocd/gocd#1459.
=> Info about proxies and agents

installation/install/agent/osx.md
Fixes #3 
There are also `go-agent-bootstrapper.log` and `go-agent-launcher.log` logfiles, I'm not sure (yet) what gets logged there.
=> Correct logging information for agent on Mac OS X

installation/install/server/linux.md
* This helps the links be longer-lived, since they're not tied to the text of the heading.
=> Use better names for some headings

installation/ssl_tls_config.md
* __As a__ security-concious maintainer of a site with custom x509 certs
* __I Want__ to use my own custom x509 certificate on my Go
Server
* __So That__ team members can reach the gocd dashboard at a secure, user-friendly URL like `https://go.mydomain.com`
* __And__ browsers will not warn users about insecure connections when
they try to use gocd's default self-signed certs
__But__: documentation on how to meet this use case is missing from the docs, and configuring the server alone as described [here](https://www.go.cd/2014/06/05/using-go-cd-with-custom-certificates.html) causes the Go Agent to fail when trying to connect to the server, because the Go Agent trust store doesn't contain the custom cert.
This PR adds documentation on how to add custom x509 certs to both the Go Server and …
=> Add guide for custom x509 certs to SSL/TLS section

installation/ssl_tls_config.md
The example bash code in pull request #17 omits the filename for the cert being inserted into the go-agent trust store.
This PR fixes that typo and provides arguments on separate lines for better readability.
=> Fix typo in PR #17

installation/install/agent/windows.md, installation/install/server/windows.md, installation/ssl_tls_config.md
SSL Configuration as a single property does not work on windows,
each ssl property has to be specified separately
=> Updated windows SSL configuration

SUMMARY.md, installation/ssl_tls/custom_certificate.md, installation/ssl_tls/setting_up_ciphers.md, installation/ssl_tls_config.md
* to setup ciphers
* to setup certificates
=> Split the SSL configuration into 2 pages —

configuration/admin_use_parameters_in_configuration.md
Change 'paramter' to 'parameter'
=> Fixed typo 'paramter'

README.md, SUMMARY.md, configuration/configuration_reference.md, extension_points/configrepo_extension.md, extension_points/index.md, package.json
* XML reference of the `<config-repos>` section with some examples
* user docs about config-repos extension point, including:
* overview of feature
* scope of what can be defined in remote pipelines
* what merging behavior is expected for groups and environments
* errors and limitations
=> Config repos user docs

advanced_usage/admin_install_multiple_agents.md
I can't say why this worked before (it definitely did) but now when trying to start the agents you get a permission denied because /etc/default/agent-1 isn't readable by the user 'go'. This change retains root:go ownership and 640 perms.
=> preserve permissions on default file

configuration/admin_add_task.md, configuration/managing_pipelines.md
While reading the documentation I noticed this duplication and decided to fix it and contribute with a PR.
=> Removing duplicated 'a' word from documentation.

installation/troubleshoot_installer.md
When user upgrade from a Go Installation using java 7 to 17.1 or higher version the upgrade will be successful, but the start up would fail since the JAVA_HOME will still be pointed to java 7. So this guide can help is user setting up the JAVA_HOME properly in both linux and windows
=> Troubleshooting guide for java 7 to java 8 based Go upgrade

installation/ssl_tls/custom_server_certificate.md
Added commands to force keystore and key passwords to match on final keystore regardless of previous passwords. Maybe 1 is unnecessary here?
=> Added explicit password flags for final keystore generation

_layouts/website/page.html, book.json
With this, you can add a header such as this (below) to a markdown file and it'll change the keywords and description metadata in the page head:
```
---
description: Page description goes here
keywords: some, key, words, here
---
```
If not provided, there's a default (same as www.gocd.org).
/cc @nyuday
=> Allow overriding meta keywords and description

advanced_usage/pipelines_as_code.md, configuration/configuration_reference.md
`id` is now a required component of `config-repo`. Fixes #110.
=> Update Pipelines as Code and Config Reference Docs for 17.8.0

introduction/concepts_in_go.md
Apologies for the disappointing first contribution, hopefully will have something more substantial in the future :wink:
["It's" is always short for "it is"](https://en.oxforddictionaries.com/usage/its-or-it-s), but since we're talking about concepts which comprise GoCD we're implying possession.
=> "it's" => "its"

configuration/dev_authorization.md
The XML fragment that defined users is invalid as it does not start with an opening users tag.
=> Fixes invalid XML when defining users

advanced_usage/pipelines_as_code.md, yarn.lock
* No longer need to install the plugins, since they are bundled.
* Also, updated yarn to v1.0.1
Will need to check that the old yarn in our images will work with this, or we need to upgrade yarn to latest there as well.
=> Fix pipelines as code docs

INTRO.md
Broken link points to deprecated documentation
=> Remove broken link

installation/configure-agent-proxy.md, installation/install/agent/linux.md
following two changes
1. Added Overriding default startup arguments and environment for linux agent
2. Corrected broken link in configure-agent-proxy.md
=>  added overide startup section for linux agent 

configuration/dev_upload_test_report.md
Discussion on (gitter yesterday](https://gitter.im/gocd/gocd?at=5a505ef2290a1f456155708d)
concluded with 
@ketan 
> The only format GoCD understands is junit. And some Versi n of nunit. 
As such  the docs should not say:
> You can use GoCD with any XUnit style xml reports
As the [xUnit style](https://xunit.github.io/docs/format-xml-v2.html), and [JUnit style](https://www.ibm.com/support/knowledgecenter/en/SSQ2R2_9.5.0/com.ibm.rsar.analysis.codereview.cobol.doc/topics/cac_useresults_junit.html)
are very different.
I assume the versions of nUnit which work are ones that are "JUnit style".
This PR is literally a single letter change.
=> Do not say that Tests support xUnit xml

installation/install/server/_install_server_footer.md
Otherwise, it is not clear, where to look for `cruise-config.xml`. 
Unfortunately, this can be confusing, cause if you're observing `/etc/go` directory with a regular user, you don't have permissions to see it.
=> Added path to `cruise-config.xml` file

advanced_usage/other_config_options.md, configuration/admin_mailhost_info.md, installation/configure-reverse-proxy.md, installation/troubleshoot_installer.md, introduction/concepts_in_go.md
I noticed that some of the in-page links were broken on [this](https://docs.gocd.org/current/introduction/concepts_in_go.html) page on Firefox 58 and Chrome 63. (E.g. the Materials link). 
The `name` attribute has been [deprecated](https://developer.mozilla.org/en-US/docs/Web/HTML/Elemqent/a) in HTML5, which is probably why they aren't working. I've replaced it with an `id` attribute.
In cases where the `id` value contains periods, the scroll was not working. This is possibly because of a bug in the way gitbook uses javascript to scroll to a section. (The links containing periods work with Javascript disabled). I have replaced the periods with hypens.
=> Use `id` attribute instead of `name` for in-page links

installation/troubleshoot_installer.md
Adding a new troubleshooting issue when starting GoCD Server and default ports are in use.
=> New troubleshooting issue when starting GoCD Server

content/faq/dev_use_current_revision_in_build.md, content/faq/environment_variables.md, content/installation/troubleshoot_installer.md, content/installation/troubleshooting.md, content/menu/index.md
This reverts commit 098d25d217e2a33c64c6b3b8f82b079c1aed0bab. Alias is not working as expected for nested pages.
=> Revert "#246 fix"

build.gocd.groovy, rakelib/publish.rake
Updated the publish task to utilize env var 'GOCD_VERSION', if present, to publish to changes to.
=> Older pipelines updated the correct version

content/faq/dev_use_current_revision_in_build.md, content/installation/troubleshooting.md, rakelib/build.rake
Bug
certain search results had undefined as the title
Reason:
missing title property
Fix:
Added task to check if title property is present on all md files excluding index.md
=> Fixed undefined title in search results

content/integration/_index.md
Fixes the images in the "integration" page:
=> Fix image links

content/_index.md
The `installed` link was redirecting to a 404 page. This change addresses this.
=> Fix installation link on Quick help section

content/advanced_usage/admin_install_multiple_agents.md, content/configuration/configuration_reference.md, content/faq/admin_out_of_disk_space.md, content/faq/dev_use_current_revision_in_build.md, content/faq/docker_container_ssh_keys.md, content/faq/material_update_hung.md, content/gocd_on_kubernetes/designing_a_cd_pipeline/creating_a_deploy_pipeline.md, content/installation/install/agent/osx.md, content/installation/install/agent/windows.md, content/installation/install/server/osx.md, content/installation/install/server/windows.md, content/installation/performance_tuning.md, content/installation/ssl_tls/setting_up_ciphers.md, package.json, themes/hugo-book/layouts/partials/docs/shared.html, yarn.lock
[I thought a [recent fix in hugo](https://github.com/gohugoio/hugo/issues/5757) would help with https://github.com/gocd/docs.go.cd/issues/320, but it did not. Since I'd done the upgrade, I decided to just keep it.]
For the upgrade to keep the content the same, I had to make some changes for:
- https://github.com/russross/blackfriday/issues/495
- https://github.com/gohugoio/hugo/issues/2928#issuecomment-359172945
The changes, after this upgrade are quite small. And, I had to leave those changes there because these were related to bugs in formatting in the old pages. For instance, you'll see issues at the end of https://docs.gocd.org/current/faq/docker_container_ssh_keys.html where formatting is broken.
The diff when this is done:
```shell
git reset --hard …
```
=> Upgrade Hugo to 0.55.6

content/configuration/secrets_management.md
=> #000 - Fix typos in secrets management docs

content/installation/configure-reverse-proxy.md
Prevented large artifacts to be uploaded through nginx reverse proxy.
=> Add client_max_body_size to nginx conf

content/extension_points/plugin_user_guide.md, content/extension_points/scm_extension.md, content/extension_points/task_extension.md
Point to plugin API docs instead.
=> Remove links to developer docs

content/configuration/configuration_reference.md
- Document allowOnlyKnownUsersToLogin flag at each authConfig level.
- Remove attribute documentation for allowOnlyKnownUsersToLogin from security.
=> Document allowOnlyKnownUsersToLogin at authConfig

content/installation/install/agent/zip.md
The heading incorrectly said these instructions related to installation of the GoCD Server, but the agent installation instructions links here, and the steps are all about the agent.
=> fixes incorrect heading: server -> agent

content/advanced_usage/agent_auto_register.md
In the latest versions file autoregister.properties has been changed from /usr/share/go-agent/config/ to /var/lib/go-agent/config/. I think it is important to know where to find it.
=> Add auto register file location

content/installation/performance_tuning.md
This is follow up of https://github.com/gocd/gocd/issues/7698 and https://github.com/gocd/gocd/pull/7736
Basically there are differences between how JVM params should be configured in `wrapper-properties.conf` for gocd agent and server. This PR makes a distinction between each inside `performance_tuning.md`
Feel free to rephrase or change however you like, but _some_ kind of distinction is needed IMO.
Thanks! :smiley:
=> Split performance_tuning.md 'Things to Remember' into sections

content/faq/fixing_common_issues.md
There isn't a single line in documentation explaining that application will no longer automatically start port 8154 (HTTPS). New users (like me) can think that application was unable to start listening on port 8154. After searching whole day I found answer "hidden" on GitHub, but I think this will be more helpfull.
=> Updating documentation with new common issue.

content/installation/install/agent/osx.md
Looks like this may have changed in the switch to the .zip deploy for Mac.
=> Change location of wrapper-properties.conf

content/installation/install/agent/osx.md, content/installation/install/server/osx.md
For https://github.com/gocd/gocd/issues/8354.
<hr>
=> [Latest release] Add quarantine instructions to Mac OS X docs

content/configuration/job_timeout.md
Job timeout was used to cancel jobs stuck at `Building` state.
Now, it will be use to cancel job which was not assigned an agent.
Updated the docs for the same.
=> Job timeout is now applicable for unassigned job

README.md, content/configuration/configuration_reference.md
The current docs are super confusing. Hopefully, this is better.
=> Make `ignoreForScheduling` docs clearer

.github/workflows/build_and_publish.yml, .github/workflows/pr_workflow.yml, README.md, package-lock.json
GH actions has been running on Node 16 as it failed to lock the version, producing warnings on build. This changes to match what it has been running with and avoid uncontrolled Node upgrades in future.
=> Correct lockfile to match NPM version currently being used

content/installation/configure-reverse-proxy.md
The proxy_buffering directive defaults to on, so every response gets buffered.
Normally thats not an issue, but when a slow client tries to download a huge file the download gets corrupted.
To prevent this from happening, the buffering of responses from GoCD must be disabled.
=> Adds info regarding download corruption in nginx

content/advanced_usage/pipelines_as_code.md
And add real-world'ish examples of the rules required for non-trivial value-stream-maps where pipelines from one config-repo may refer to pipelines in a different pipeline group defined in a different config-repo.
=> Re-organise the rules section of the pipelines as code section

layouts/partials/installation/install/_apt_repo.md
apt-key has been deprecated and should no longer be used. This updated process ensures that GoCD's key will only be applied to packages in GoCD's repository.
=> Remove apt-key reference

content/configuration/dev_authorization.md
There was a duplicate word ("is") in the following sentence:
- Original: "Note that is is possible to give a user or role only the operate permission."
- Updated: "Note that it is possible to give a user or role only the operate permission."
=> Fix typo dev_authorization.md
